Version1
Brindha-Josh/CustomerAPI pull request #3
Opened 2019-12-20 11:58 UTC by Brindha-Josh

I have updated the coding as per ur changes and created pull request again
1.Removed  CUSTOMERAPISQL.csproj.user: in git
2.Activated the route [Route("")]
3.The namespace should not be in all capitals.. (change in all your code-files)-Updated to CustomerMgmt
4.Customer1Controller is renamed as CustomerController
5.removed  the  Route [Route("")] in  Controllers/Customer1Controller.cs: for Edit/Delete/Post
6.In Controllers/LoginController.cs: removed Post route-name
7.In Models/Customer1.cs:-renamed as Customer
8.In Models/UserModel.cs:-Aligned the coding.

2019-12-20 13:10 UTC, perkare commented
Some comments: 
-You should not remove the .csproj file. Only the .csproj.user file
- Make sure the branch builds and has no failing checks (the pull request nor reports 2 failing checks)

2019-12-20 23:46 UTC, perkare requested changes
A few more issues to fix:

- Delete /Models/Customers.cs (this is not in use is it?)
- Rename /Models/UserModel.cs to /Models/User.cs
- Align code ("format document") in /Startup.cs
- Remove out commented code in /Startup.cs
- You can probably remove the code in  `endpoints.MapControllers(...)` and  replace it with `app.UseMvcWithDefaultRoute();` in Startup.cs? (please correct me if I am wrong)
- Why do you have two azure-pipelines files? Do you need both?

2019-12-20 23:46 UTC, perkare commented on Controllers/CustomerController.cs
> +    [Route("")]
You can remove this. Here and all other places you may have used it. Use conventional routing.
Use app.UseMvcWithDefaultRoute(); in Startup.cs
See https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1

2019-12-27 13:47 UTC, perkare commented
Why are you adding CustomerData.cs as a data access layer when you already are using EntityFramework for this? Can you remove this and use your existing data-context instead?

2019-12-28 11:25 UTC, Brindha-Josh commented
Hi
I was just trying to fetch data using that method.will delete that form and
try to access use that entity layer.will upload the form in git hub.

Regards
Brindha


On Fri, 27 Dec 2019, 2:47 pm Per Kåre Otteren, <notifications@github.com>
wrote:

> Why are you adding CustomerData.cs as a data access layer when you already
> are using EntityFramework for this? Can you remove this and use your
> existing data-context instead?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Brindha-Josh/CustomerAPI/pull/3?email_source=notifications&email_token=ANUAPB5XN4Y4QCUUIULIO63Q2YBQHA5CNFSM4J547VTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXG3ZQ#issuecomment-569273830>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANUAPB67Y77PJQ2YC34WV7DQ2YBQHANCNFSM4J547VTA>
> .
>

2020-01-03 10:36 UTC, perkare approved these changes

2020-01-03 10:37 UTC, merged